thoroughcare-app:
  web:
    container_size:
      down: 1024
      up: 4096
    container_count:
      down: 1
      up: 4
  worker:
    container_size:
      down: 1024
      up: 4096
    container_count:
      down: 1
      up: 1
tc-test:
  web:
    container_size:
      down: 512
      up: 1024
    container_count:
      down: 0
      up: 1
  worker:
    container_size:
      down: 512
      up: 2048
    container_count:
      down: 0
      up: 1
tc-staging:
  web:
    container_size:
      down: 512
      up: 1024
    container_count:
      down: 0
      up: 1
  worker:
    container_size:
      down: 512
      up: 1024
    container_count:
      down: 0
      up: 1
tc-scale:
  web:
    container_size:
      down: 512
      up: 1024
    container_count:
      down: 0
      up: 1
  worker:
    container_size:
      down: 512
      up: 1024
    container_count:
      down: 0
      up: 1
